### ISSUE TITLE
First run: Got error

### ISSUE THREAD

**Issue by orta** [damassi/react-styled-components-for-designers#1]
I _just_ ran:

```
git clone git@github.com:damassi/react-styled-components-for-designers.git
cd react-styled-components-for-designers
npm install -g yarn
yarn install
yarn start
```

and got:

<img width="1043" alt="screen shot 2018-01-29 at 1 16 03 pm" src="https://user-images.githubusercontent.com/49038/35526820-b013e86e-04f6-11e8-896f-320f162161d1.png">

**Comment by orta** [comment]
Looks like it's not in the package.json

**Comment by damassi** [comment]
@orta - Just noticed that as well; looks like the package depends on babel and not in `package.json`, gonna open a PR over there

**Comment by damassi** [comment]
@orta - can you try again?

**Comment by orta** [comment]
Confirmed, works
